### ISSUE TITLE
Communication channel and version 2.0 discussion

### ISSUE THREAD

**Issue by Th3Mouk** [tbolier/php-rethink-ql#46]
Hi !

Do you have a chat or something to communicate with you ? I miss some function like `now`, `hasFields`, `distinct`, `map`, `contains`, `without`, `merge`, `add`, `sub`, `not`, `ISO8601`.
I would like to implement them, but I'm stuck to implement among others `now`, `add`, and `not`.
I don't have your logic and the way of thinking of this lib.

Thanks

**Comment by tbolier** [comment]
Hey @Th3Mouk 

Thanks for your interest, would be great to work together on this.

Which communications do you prefer, we can do skype, hangouts, or slack.

One of my to-do's is to create issues for each missing feature of the rethinkDB api.

I am looking forward in speaking with you.

Timon

**Comment by Th3Mouk** [comment]
Yeah creating issues can be a good idea because all the threads will be public, it can be simpler for everyone. A slack can be a good solution too because i'm on it 24/7 and it's easier to sort out problem with asynch chat.

**Comment by tbolier** [comment]
Hey @Th3Mouk I have created a issue template, and created the first issues regarding missing features now. Would you like to help using these as the template reference for creating the missing features as an issue? From there we can discuss each new feature, individually. Next to the comunications via the Github issues, I propose to start a slack room in the current rethinkDB slack. However I need to obtain an invite to their slack group. I will request this and invite you in there afterwards.

**Comment by tbolier** [comment]
@Th3Mouk @marcgeurts @AxaliaN Can you guys please check the roadmap 2.0 
https://github.com/tbolier/php-rethink-ql/blob/master/docs/roadmap.md

And verify if there are any functionalities that we would like to add for version 2.0 milestone?

**Comment by Th3Mouk** [comment]
Can u please add to the milestone `ge`, `le`, `not` ?

**Comment by Th3Mouk** [comment]
Awesome work, thank for the issues

**Comment by tbolier** [comment]
@Th3Mouk Yes we can, I will do it tonight.

Unfortunately nobody is responding in IRC #rethinkdb so we will probably not have a slack channel soon in there. Can we go into direct communications for now? Maybe via skype, or any other chat, what do you prefer?

**Comment by tbolier** [comment]
Hey @Th3Mouk I have added you as collaborator and added the issue for ge, le and not.

https://github.com/tbolier/php-rethink-ql/issues/60

**Comment by Th3Mouk** [comment]
What about a discord or a gitter ? I remember some repos had one gitter with an img tag on the readme

**Comment by tbolier** [comment]
Hey @Th3Mouk

Yes lets do one of those and get the development for version 2.0 on the road. I will create a channel and invite you to it.

Thanks for thinking along!

**Comment by tbolier** [comment]
Hey @Th3Mouk 

I have created a room in spectrum.chat under the rebirthdb community
https://spectrum.chat/thread/63f2fcf5-edf4-493e-9b9b-da4ab687aef3

Since rethinkdb and most drivers including this php driver were also forked under the rebirthdb community (initiative), I was also invited to join their spectrum chat.

Of course we will support both rethinkdb and rebirthdb from now on. However, to keep the communition for both aligned, we can maybe use that room for initial communications to keep it central within the community.

Can you join via this link?
https://spectrum.chat/thread/63f2fcf5-edf4-493e-9b9b-da4ab687aef3

**Comment by tbolier** [comment]
Hi @Th3Mouk and all,

Since spectrum chat for RebirthDB is still upcoming, I've also created a gitter room.

https://gitter.im/rethinkdb-php/Lobby

Please join us!
