### ISSUE TITLE
Improve interface segregation for ReQL query commands

### ISSUE THREAD

**Issue by tbolier** [tbolier/php-rethink-ql#47]
## Issue summary

Each function in the RethinkDB API (ReQL commands) has a set of commands in the return type interface that can be called (chained / fluent interface).

We need to improve the simplicity of the ReQL query command interface segregation. Currently the interface inheritance is really confusing for current and new developers and might violate the interface segregation SOLID principle in near future.

It is easy to make a mistake at the moment by using the wrong interface as a return type of a ReQL command. Favourable each function will return it's own interface with it's own set of (submodules) functions.

For more information about interface segregation, see:
https://www.oodesign.com/interface-segregation-principle.html

## Issue checklist
- [x] Propose interface segregation
- [x] Implement new interfaces

The following sections can be removed only, whenever they are not applicable or you have a simple question.

## Actual Behavior

What is it doing now?
- We have too much confusing interfaces.
- New API functions might not support all methods in our current query interfaces. Causing polluted interfaces and violating the interface segregation SOLID principle.

## Expected Behavior

- A new ReQL command should be easy to implement.
- Current and new ReQL commands should favourable have their own segregated interface.

**Comment by Th3Mouk** [comment]
Currently i've seen 11 differents interfaces:

We could use them in return of operators to improve the autocomplete too

* RethinkInterface [db](https://www.rethinkdb.com/api/javascript/db/)
* TableInterface [between](https://www.rethinkdb.com/api/javascript/between/)
* ValueInterface [not](https://www.rethinkdb.com/api/javascript/not/)
* BoolInterface [eq](https://www.rethinkdb.com/api/javascript/eq/)
* SequenceInterface [eq_join](https://www.rethinkdb.com/api/javascript/eq_join/)
* StreamInterface [zip](https://www.rethinkdb.com/api/javascript/zip/)
* ArrayInterface [zip](https://www.rethinkdb.com/api/javascript/zip/)
* SelectionInterface [order_by](https://www.rethinkdb.com/api/javascript/order_by/)
* BinaryInterface [count](https://www.rethinkdb.com/api/javascript/count/)
* StringInterface [count](https://www.rethinkdb.com/api/javascript/count/)
* ObjectInterface [count](https://www.rethinkdb.com/api/javascript/count/)

**Comment by tbolier** [comment]
That is a good idea @Th3Mouk , but will the return type not mismatch with the PHPdoc in that case?

**Comment by Th3Mouk** [comment]
It can, but now with PHP7.1 return types and nullable, phpdoc is not so relevant, I omit personally some informations that already appear in the method signature. It seems that I don't really understand the purpose of this issue, is the aims about split current interface ? And create new "MetaInterface" ?

**Comment by tbolier** [comment]
Hey @Th3Mouk 

I agree fully on PHPdocs, according to clean code we should always use meaningful names and functions. PHPdocs are optional with PHP7 strict types.

This issue is not meant for that case however. 

ReQL has different return methods for different functions, since the interface is mostly fluent, using shared or compound interfaces causes a complex problem of which interface to implement and keeping the return types correct.

By creating more interfaces for each specific method or method type, we can manage the interfaces more easy, and keep interface segregation satisfied as much as possible.

I think beyond the current implementation the extending of interfaces is becoming problematic to comprehend.

**Comment by tbolier** [comment]
## Approach
The interfaces and compound interfaces were too confusing to comprehend.

## Research
I wanted to eliminate the inheritance in the interfaces, and have one interface per object, no more interface inheritance or compound interfaces. This will simplify the understanding of what return type to use. I also wanted to eliminate the huge inheritance chain on some object.

## Solution
So I have decided to move the reusable methods to traits and eliminated the interfaces completely, since you have a direct contract anyway with the called method return type.

**Comment by tbolier** [comment]
The solution has been implemented.
