### ISSUE TITLE
RebirthDB

### ISSUE THREAD

**Issue by thelinuxlich** [tbolier/php-rethink-ql#58]
Hey tbolier! I don't know if your driver already supports fully the 2.3 version, but we've forked RethinkDB to release a 2.4 version and all drivers will have separate repositories under our organization, discussion here: https://spectrum.chat/rebirthdb

So I'm inviting you to join us, there you can have more visibility for your project, what do you think?

**Comment by tbolier** [comment]
Hi @thelinuxlich 

Awesome, that would be great. Our driver is in continuous development, we do not support all API features yet, but our next version is plannen for the end of july. See our roadmap under the docs folder.

I will join in on the conversation, thank you!

**Comment by tbolier** [comment]
I have created a fork under the rebirthdb project, thank you for the invitation. I will join the further conversations.
