### ISSUE TITLE
how to implement the driver in a project?

### ISSUE THREAD

**Issue by Slluxx** [tbolier/php-rethink-ql#67]
Hey, i just wanted to know how i include this in my project I never had to use "use" / namespaces.
I am only getting errormessages like : 
`Fatal error: Uncaught Error: Class 'TBolier\RethinkQL\Registry' not found in`

Hope you dont mind explaining it to to me.

**Comment by Th3Mouk** [comment]
You need to use composer to download the library
`composer req tbolier/php-rethink-ql` [here on packagist](https://packagist.org/packages/tbolier/php-rethink-ql)

Then in your project I hope you are using the autoloader of composer too.
If not use this line.
`require_once __DIR__ . '/vendor/autoload.php';`

After this you can you can use classes of the project easily.
If you aren't familiar with autoloading have a look [here](https://getcomposer.org/doc/01-basic-usage.md#autoloading)

Feel free to ask if my explanations are not clear

**Comment by Slluxx** [comment]
Currently at work but i will test this asap. thanks!

**Comment by tbolier** [comment]
Thanks for answering @Th3Mouk 

Let us know how it worked out @Slluxx

**Comment by Slluxx** [comment]
Hey @tbolier 
I gave it a try today but i am unable to set it up. Maybe you can take a look at it.

`Fatal error: Uncaught TBolier\RethinkQL\Connection\ConnectionException: The connection default_connection does not exist.`

PHPStorm also gives me following info:
`Unhandled \TBolier\RethinkQL\Connection\ConnectionException
Inspection info: The inspection reports exceptions which are neither enclosed in a try-catch block nor documented using the '@throws' tag`

```php
<?php
require_once __DIR__ . '/vendor/autoload.php';
use TBolier\RethinkQL\Rethink;
use TBolier\RethinkQL\Connection\Registry;
$connections = [
    'default_connection' => [
        'host' => 'localhost',
        'port' => 28015,
        'default_db' => 'mactests',
        'user' => 'admin',
        'password' => '',
        'timeout' => 5,
        'timeout_stream' => 10,
    ]
];
$registry = new Registry( $connections );
$r = new Rethink( $registry->getConnection( 'default_connection' ) );
$r->connection()->connect();
```
