### ISSUE TITLE
2.0 release - changes function

### ISSUE THREAD

**Issue by sebam91** [tbolier/php-rethink-ql#79]
Hello,
Are there any approximate plans of 2.0 release?

Desperately waiting for php library with changes function :)

**Comment by tbolier** [comment]
Hey @sebam91 the changes function is available in the latest release.

I've been so busy with work that version 2.0 has huge delays!

But you should be able to use changes immediately with the latest release at packagist.

**Comment by tbolier** [comment]
See https://github.com/tbolier/php-rethink-ql/releases

**Comment by sebam91** [comment]
> Hey @sebam91 the changes function is available in the latest release.
> 
> I've been so busy with work that version 2.0 has huge delays!
> 
> But you should be able to use changes immediately with the latest release at packagist.

@tbolier Thanks for the information!

**Comment by tbolier** [comment]
@sebam91 You're more than welcome!
